data_dir: /data/scoresheets/dataset/object_detection/default/train/
output_dir: /data/scoresheets/models/object_detection/default/
label_map_path: /data/scoresheets/models/object_detection/default/label_map.pbtxt
faces_only: True
mask_type: png
num_shards: 2
